Repository KieranDevlin/thrival, pull requests merged in 2020-04, with the labels that each got.

#4 Ivan prisma setup
  server/datamodel.prisma
  server/docker-compose.yml
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/index.js
  server/generated/prisma-client/prisma-schema.js
  server/index.js
  server/package.json
  server/prisma.yml
  server/resolvers.js
  server/typeDefs.js
  server/yarn.lock
Labels: bug, enhancement

#7 Fixes connection to docker server
  client/config/api.js
  client/lib/screens/AddJobPost/AddJobPost.js
  client/lib/screens/AddJobPost/AddJobPostContainer.js
  client/lib/screens/AddJobPost/index.js
  client/lib/screens/AddJobPost/styles.js
Labels: bug

#27 add calendar screen and basic daypicker
  client/lib/screens/Calendar/Calendar.js
  client/package.json
  client/yarn.lock
Labels: enhancement
